### ISSUE TITLE
viewing item database and monster database problem.

### ISSUE THREAD

**Issue by bgamez23** [missxantara/fluxcp-ra#8] opened 2013-07-21 11:27 UTC
the current version of fluxcp-ra is now having an issue regarding on viewing the database.

**Comment by bgamez23** [comment] 2013-07-21 11:43
and also can you make it compatible with hercules database?

**Comment by bgamez23** [comment] 2013-07-22 02:58
up

**Comment by jTynne** [comment] 2013-07-23 19:50
Also finding that this is no longer working with the latest version of rAthena or Hercules.

**Comment by bgamez23** [comment] 2013-07-24 01:00
yah your right. i hope it would be fix.

**Comment by missxantara** [comment] 2013-07-24 02:33
Hmm.. I didn't get an email notification for when this bug was created but only until jTynne commented o_o

Anyways, I'll take a look. But since this is "FluxCP for rAthena", I am only going to fix it to work for rA. If the fix also works for Hercules, then great but I won't be making further effort to make it also compatible for Hercules.

Edit: Oh, and thanks for reporting the bug =)

**Comment by missxantara** [comment] 2013-07-24 03:55
Hmm... I'm unable to reproduce. I have the latest FluxCP-rA, queried the latest rA SQL database files and I am able to view both the list and specific items/mobs. Tried both RE and pre-RE.

I'm marking this as "invalid" but will keep the issue open for a while. Please let me know in detail on what is not working. If there is an error shown on the screen, please also provide that. Thanks!

**Comment by jTynne** [comment] 2013-07-24 03:59
Do you have any plans to extend this project to also be inclusive to Hercules, or should I ask someone to re-write the module to be compatible? :o

**Comment by missxantara** [comment] 2013-07-24 04:18
If you ask this prior to yesterday, I would have said no xD But I have recently been asked to support Hercules in my other works so I've given it some thought. It all depends on how the Hercules' admins answers my question on their dedication to the project and name. I've sent a PM regarding this yesterday but I have not since had a response. Since you are close(r) to them, why don't you give them a nudge? ;)

**Comment by jTynne** [comment] 2013-07-24 04:22
Who specifically did you try contacting? As far as I'm aware, everyone's very much dedicated to the emulator (I wouldn't have switched to it from rAthena if otherwise XD). I'll drop a message in the staff chat. :)

**Comment by missxantara** [comment] 2013-07-24 04:25
I messaged Ind but added Jman to the conversation earlier today.

**Comment by bgamez23** [comment] 2013-07-24 18:35
wtf?invalid?hmmm its ok. i already make a fix for my copy.

**Comment by jTynne** [comment] 2013-07-24 18:37
Can you share, bgamez23 over on the Herc forum? A lot of people are missing out on this functionality who don't know how to make the edit themselves.

**Comment by missxantara** [comment] 2013-07-25 03:39
If it is a bug (on rA), then I want to know so that I can fix it. I left the issue open because of this. So please, if you are able to reproduce the problem, let me know so that the rest of the people can run it without difficulties. Maybe I am just testing it incorrectly but saying "its ok, i have a fix" defeats the point in creating the issue and doesn't help the development of the project =(

**Comment by bgamez23** [comment] 2013-07-27 00:45
@jTynne i already posted it on Hercules to make it compatible with. since fluxcp-ra is not compatible with hercules. as of now still not supported renewal.
http://hercules.ws/board/topic/1747-hercules-fluxcp/

@missxantara the problem was on the sql. since hercules use atk instead of attack. that why its having an issue regarding on that.

**Comment by missxantara** [comment] 2013-07-27 04:31
Oh, so it wasn't an rA bug? Great, I'll close this issue then.

@others, if you are an rA user and experience a DB bug, please still report it. Thanks!

**Closed as completed by missxantara** 2013-07-27 04:31 UTC
Labels: invalid
